/***** THIS CREATES THE TABLE DESIGNED TO CONTAIN THE MONTHLY SCE CAPITAL EXPENSE SUMMARY *****/

USE [SONGS]
GO

DROP TABLE dbo.idxINV_SCE_CAP_Summary;

CREATE TABLE dbo.idxINV_SCE_CAP_Summary
	(
	RecordID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Invoice_Key CHAR(6) NOT NULL,
	SCECostGroup_Short VARCHAR(15) NULL,
	SCEProjectID VARCHAR(10) NULL,
	WBSElement VARCHAR(25) NULL,
	SCEOrderNumber VARCHAR(9) NULL,
	SCELocation CHAR(4) NULL,
	SCEFunction CHAR(4) NULL,
	SCEExp CHAR(5) NULL,
	SCEPeriod VARCHAR(7) NULL,
	DirectLabor_SONGS MONEY NULL,
	DirectTotal_SONGS MONEY NULL,
	LoadedTotal_SONGS MONEY NULL,
	LoadedTotal_SCE MONEY NULL,
	LoadedTotal_SDGE MONEY NULL,
	LoadedTotal_RIV MONEY NULL,
	LoadedTotal_ANA MONEY NULL,
)

GO


