USE [SONGS]
GO
BACKUP DATABASE [SONGS] TO  DISK = N'G:\DEV_BACKUP00\BACKUP\SONGS_BAK' WITH NOFORMAT, NOINIT,  NAME = N'SONGS-Full Database Backup', SKIP, NOREWIND, NOUNLOAD,  STATS = 10;
GO
BACKUP LOG [SONGS] TO DISK=N'G:\DEV_BACKUP00\BACKUP\SONGS_LOG_BAK' WITH NOFORMAT;
GO
DBCC SHRINKFILE(N'SONGS_log',0,TRUNCATEONLY);
GO
DBCC SHRINKFILE(N'SONGS_log',0,TRUNCATEONLY);
DBCC SHRINKFILE(N'SONGS',0,TRUNCATEONLY);
GO
sp_helpfile
GO