USE [SONGS]
GO

ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_SCEProject VARCHAR(10) NULL;
ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_PlanCategory CHAR(3) NULL;
ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_Date_CNCLD DATETIME NULL;
ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_Date_ENGZD DATETIME NULL;
ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_Date_ECD DATETIME NULL;
ALTER TABLE [dbo].[SDGE_SAP_KOB1] ADD OII_Status VARCHAR(15) NULL;

SET ANSI_PADDING OFF
GO


